
sudo: required
services:
- docker
before_install:
- docker pull node:8-onbuild
install:
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
- docker run --rm probot-hello npm run lint
deploy:
  provider: heroku
  api_key:
    secure: CbQJnIHm3HOPke6GP9ye6v/9aS/XRPHqa6eRrtoHJ9LieBpd2HHGIXAAI++OhvdNpcldj1Bj/36ZDCMj3yUZpyd/0Mg1KNzLcHz+Og0AZXfPdpVJrSXHQh5UQeh9IgHWayC07zyYxYKgLMu3qaoUVU6aSOgQsp9SXeFx0i0m6SEZkk6gyf23vLbrA/w3v86O/RSB282oB4l3DOBMfX39GKGH5HsVygWtz0XSsm+rzgOmND2TFyunHEtxUMN5l2jAQ1YXeywSzVW+O1Yux51pcIQ3aCZAekpF8hciraZlGuUU/IZoiobIWhr++zulxkiTs9pZbjaVFXPVxSl4+4ctw1vIAbLijDdpQQjFEZO/bvc+Jw0B9TyI2btqqkAiVutJOGEv7kObjtNaCAgnDwMDHh+lwaPBuWDY4WBmK5GgXikJEWfpAyd2P6LUBI5ykDgPheO/4Wxc/cUwLSS0+lftjF8RIynXKsb62lSygHSm1O97c1LwRO12lKvJpldmz8pUkhQbzLj6E8WJQhOXCIRjLRJ56ugBwHbq11rY/2D1G2L8TRAyOYtvrCQaj85U4Q3MXxvIkNiCq/WjMNPwtOTcX8pel6MRjUO/Fdn5DaqyzY1SSKFjv/l8UHkpXspgLDgHD6NtA1c8Tl2y0yPSMz5Q3t19DfxROoGpXE3ItqACkZM=
  on: heroku_production
  app: probot-pkill2913 